### PR TITLE
no need add -std=c99 -D_BSD_SOURCE compile flag in makefile

### PR DESCRIPTION
**Pull request by nfer**
remove "-std=c99 -D_BSD_SOURCE" and update udp_sender.c

### CODE REVIEW

**Comment by Shippo7** [comment]
Hi net,

The -std=c99 -D_BSD_SOURCE compile flags are useful for cc compiler on Linux. Without -D_BSD_SOURCE, gcc compiler will not compile the codes successful.

You can remove -D_BSD_SOURCE on MAC OS, because MAC OS using LLVM instead of gcc when you using gcc command.

Your change on udp_sender.c breaks C89 rules. It is ok with LLVM on MAC OS, but the user will get warning message with gcc on Linux.

**Comment by Shippo7** [comment]
* Hi nfer,

**Comment by nfer** [comment]
It actually works fine.  None warring message was shown.
The key is "Declare all variables before any statement."
You could merge the patch and do the compile.

**Comment by Shippo7** [comment]
I tested the codes on CentOS 5, what operating system are you using?

**Comment by ericyangxf** [comment]
I will test your patch 2 weeks later, I am travelling right now

**Comment by nfer** [comment]
Ubuntu 12.04.

**Comment by ericyangxf** [comment]
Thanks

**Pull request merged**
